import Head from 'next/head'
// import '@/tailwind.config'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dror Maman Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <section className="bg-blue-700 h-screen">
        hello
        </section>

      </main>
    </>
  )
}
