import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from "react";
import IconLink from "@/components/IconLink";

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	
	
	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Dror Maman Portfolio</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			
			<main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
				<section className="h-screen">
					<nav className="py-10 mb-12 flex justify-between dark:text-white">
						<h1 className="text-xl font-burtons">developedbyDror</h1>
						<ul className="flex items-center">
							<li>
								<BsFillMoonStarsFill onClick={() => setDarkMode(prev => !prev)} className="cursor-pointer text-2xl"/>
							</li>
							<li>
								<a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">Resume</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-10">
						<h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">Dror Maman</h2>
						<h3 className="text-2xl py-2 md:text-3xl dark:text-white">Full Stack Developer</h3>
						<p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
							Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
						<IconLink Icon={AiFillGithub} link='https://github.com/drormaman' />
						<IconLink Icon={AiFillLinkedin} link='https://www.linkedin.com/in/dror-maman-2829111b6' />
						<IconLink Icon={AiFillTwitterCircle} link='https://twitter.com/dror_maman' />
					</div>
					<div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 m-20 mx-auto overflow-hidden md:h-96 md:w-96">
						<Image src={deved} fill className="object-cover"/>
					</div>
				</section>
				
				<section>
					<div>
						<h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
						<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
							Lorem ipsum is placeholder text <span className="text-teal-500">commonly used in the graphic</span>, print, and publishing industries for previewing layouts and visual mockups.
						</p>
						<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
							Lorem ipsum is placeholder text <span className="text-teal-500 ">commonly used in the graphic</span>, print, and publishing industries for previewing layouts and visual mockups.
						</p>
					</div>
					<div className="lg:flex gap-10">
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image src={design} width={100} height={100} className="mx-auto"/>
							<h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
							<p className="py-2">
								Lorem ipsum is placeholder text commonly used in the graphic
							</p>
							<h4 className="py-4 text-teal-600">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Figma</p>
							<p className="text-gray-800 py-1">Illustrator</p>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image src={code} width={100} height={100} className="mx-auto"/>
							<h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
							<p className="py-2">
								Lorem ipsum is placeholder text commonly used in the graphic
							</p>
							<h4 className="py-4 text-teal-600">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Figma</p>
							<p className="text-gray-800 py-1">Illustrator</p>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image src={consulting} width={100} height={100} className="mx-auto"/>
							<h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
							<p className="py-2">
								Lorem ipsum is placeholder text commonly used in the graphic
							</p>
							<h4 className="py-4 text-teal-600">Design tools I use</h4>
							<p className="text-gray-800 py-1">Photoshop</p>
							<p className="text-gray-800 py-1">Figma</p>
							<p className="text-gray-800 py-1">Illustrator</p>
						</div>
					</div>
				</section>
				
				<section className="py-10">
					<div>
						<h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
						<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
							Lorem ipsum is placeholder text <span className="text-teal-500">commonly used in the graphic</span>, print, and publishing industries for previewing layouts and visual mockups.
						</p>
					</div>
					<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
						<div className="basis-1/3 flex-1">
							<Image src={web1} className="rounded-lg object-cover" width="100%" height="100%" layout="responsive" />
						</div>
						<div className="basis-1/3 flex-1">
							<Image src={web2} className="rounded-lg object-cover" width="100%" height="100%" layout="responsive" />
						</div>
						<div className="basis-1/3 flex-1">
							<Image src={web3} className="rounded-lg object-cover" width="100%" height="100%" layout="responsive" />
						</div>
						<div className="basis-1/3 flex-1">
							<Image src={web4} className="rounded-lg object-cover" width="100%" height="100%" layout="responsive" />
						</div>
						<div className="basis-1/3 flex-1">
							<Image src={web5} className="rounded-lg object-cover" width="100%" height="100%" layout="responsive" />
						</div>
						<div className="basis-1/3 flex-1">
							<Image src={web6} className="rounded-lg object-cover" width="100%" height="100%" layout="responsive" />
						</div>
					</div>
				</section>
			
			</main>
		</div>
	)
}
